name: build-noyatu sono 2
run-name: ${{ github.actor }} is learning GitHub Actions dayo
on: [push]
jobs:
  sannity_check:
    runs-on: ubuntu-latest
    name: bakamitai
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: bash scripts/test-2.sh
