name: Deployment 
run-name: ${{ github.actor }} is deploying
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      #url: https://example.com?stating
      #hoge: fuga
    steps:
      - name: deploy
        run: echo "setart deploying ${{ github.ref }}"
